In [17]:
# Dependencies
import numpy as np
import pandas as pd

# Python SQL toolkit and Object Relational Mapper
import sqlalchemy, os
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func, inspect

from sqlalchemy import extract

In [18]:
# Change the connection to work better with my setup and system
hawaii_path = os.path.join("Resources", "hawaii.sqlite")

# engine = create_engine("sqlite:///hawaii.sqlite")
engine = create_engine(f"sqlite:///{hawaii_path}")

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

In [19]:
# Create our session (link) from Python to the DB
session = Session(engine)

In [20]:
inspector = inspect(engine)
inspector.get_table_names()

['measurement', 'station']

In [21]:
columns = inspector.get_columns('measurement')
for column in columns:
    print(column)

{'name': 'id', 'type': INTEGER(), 'nullable': False, 'default': None, 'autoincrement': 'auto', 'primary_key': 1}
{'name': 'station', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}
{'name': 'date', 'type': TEXT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}
{'name': 'prcp', 'type': FLOAT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}
{'name': 'tobs', 'type': FLOAT(), 'nullable': True, 'default': None, 'autoincrement': 'auto', 'primary_key': 0}

In [22]:
results = engine.execute("SELECT * FROM measurement WHERE date >= '2017-06-01' AND date <= '2017-06-30'")
for item in results:
    print(item)

(2644, 'USC00519397', '2017-06-01', 0.0, 79.0)
(2645, 'USC00519397', '2017-06-02', 0.0, 79.0)
(2646, 'USC00519397', '2017-06-03', 0.02, 79.0)
(2647, 'USC00519397', '2017-06-04', 0.0, 79.0)
(2648, 'USC00519397', '2017-06-05', 0.0, 80.0)
(2649, 'USC00519397', '2017-06-06', 0.0, 79.0)
(2650, 'USC00519397', '2017-06-07', 0.0, 79.0)
(2651, 'USC00519397', '2017-06-08', 0.0, 80.0)
(2652, 'USC00519397', '2017-06-09', 0.0, 80.0)
(2653, 'USC00519397', '2017-06-10', 0.04, 77.0)
(2654, 'USC00519397', '2017-06-11', 0.08, 79.0)
(2655, 'USC00519397', '2017-06-12', 0.02, 83.0)
(2656, 'USC00519397', '2017-06-13', 0.0, 80.0)
(2657, 'USC00519397', '2017-06-14', 0.0, 80.0)
(2658, 'USC00519397', '2017-06-15', 0.0, 78.0)
(2659, 'USC00519397', '2017-06-16', 0.0, 79.0)
(2660, 'USC00519397', '2017-06-17', 0.0, 80.0)
(2661, 'USC00519397', '2017-06-18', 0.05, 77.0)
(2662, 'USC00519397', '2017-06-19', 0.0, 80.0)
(2663, 'USC00519397', '2017-06-20', 0.02, 78.0)
(2664, 'USC00519397', '2017-06-21', 0.0, 79.0)
(2665, 'USC00519397', '2017-06-22', 0.0, 80.0)
(2666, 'USC00519397', '2017-06-23', 0.0, 78.0)
(2667, 'USC00519397', '2017-06-24', 0.06, 80.0)
(2668, 'USC00519397', '2017-06-25', 0.0, 80.0)
(2669, 'USC00519397', '2017-06-26', 0.0, 81.0)
(2670, 'USC00519397', '2017-06-27', 0.0, 80.0)
(2671, 'USC00519397', '2017-06-28', 0.0, 79.0)
(2672, 'USC00519397', '2017-06-29', 0.0, 79.0)
(2673, 'USC00519397', '2017-06-30', 0.08, 75.0)
(5373, 'USC00513117', '2017-06-01', 0.03, 76.0)
(5374, 'USC00513117', '2017-06-02', 0.1, 76.0)
(5375, 'USC00513117', '2017-06-03', 0.2, 76.0)
(5376, 'USC00513117', '2017-06-04', 0.15, 78.0)
(5377, 'USC00513117', '2017-06-05', 0.0, 76.0)
(5378, 'USC00513117', '2017-06-06', 0.0, 75.0)
(5379, 'USC00513117', '2017-06-07', 0.0, 75.0)
(5380, 'USC00513117', '2017-06-08', 0.02, 76.0)
(5381, 'USC00513117', '2017-06-09', 0.02, 78.0)
(5382, 'USC00513117', '2017-06-10', 0.21, 75.0)
(5383, 'USC00513117', '2017-06-11', 0.24, 73.0)
(5384, 'USC00513117', '2017-06-12', 0.19, 76.0)
(5385, 'USC00513117', '2017-06-13', 0.36, 76.0)
(5386, 'USC00513117', '2017-06-14', 0.27, 76.0)
(5387, 'USC00513117', '2017-06-15', 0.17, 77.0)
(5388, 'USC00513117', '2017-06-16', 0.02, 76.0)
(5389, 'USC00513117', '2017-06-17', 0.35, 77.0)
(5390, 'USC00513117', '2017-06-18', 0.25, 72.0)
(5391, 'USC00513117', '2017-06-19', 0.05, 77.0)
(5392, 'USC00513117', '2017-06-20', 0.05, 75.0)
(5393, 'USC00513117', '2017-06-21', 0.02, 82.0)
(5394, 'USC00513117', '2017-06-22', 0.1, 77.0)
(5395, 'USC00513117', '2017-06-23', 0.0, 76.0)
(5396, 'USC00513117', '2017-06-24', 0.0, 74.0)
(5397, 'USC00513117', '2017-06-25', 0.08, 73.0)
(5398, 'USC00513117', '2017-06-26', 0.02, 77.0)
(5399, 'USC00513117', '2017-06-27', 0.0, 77.0)
(5400, 'USC00513117', '2017-06-28', 0.01, 77.0)
(5401, 'USC00513117', '2017-06-29', 0.03, 76.0)
(5402, 'USC00513117', '2017-06-30', 0.04, 74.0)
(7566, 'USC00514830', '2017-06-01', 0.0, 81.0)
(7567, 'USC00514830', '2017-06-02', 0.15, 78.0)
(7568, 'USC00514830', '2017-06-03', 0.16, 80.0)
(7569, 'USC00514830', '2017-06-04', 0.05, 79.0)
(7570, 'USC00514830', '2017-06-05', 0.02, 81.0)
(7571, 'USC00514830', '2017-06-06', 0.0, 80.0)
(7572, 'USC00514830', '2017-06-07', 0.0, 81.0)
(7573, 'USC00514830', '2017-06-08', 0.01, 79.0)
(7574, 'USC00514830', '2017-06-09', 0.0, 81.0)
(7575, 'USC00514830', '2017-06-10', 0.53, 78.0)
(7576, 'USC00514830', '2017-06-11', 0.14, 79.0)
(7577, 'USC00514830', '2017-06-12', 0.35, 79.0)
(7578, 'USC00514830', '2017-06-13', 0.1, 75.0)
(7579, 'USC00514830', '2017-06-14', 0.21, 79.0)
(7580, 'USC00514830', '2017-06-15', 0.3, 78.0)
(7581, 'USC00514830', '2017-06-16', 0.02, 80.0)
(7582, 'USC00514830', '2017-06-17', 0.02, 78.0)
(7583, 'USC00514830', '2017-06-18', 0.18, 77.0)
(7584, 'USC00514830', '2017-06-19', 0.19, 78.0)
(7585, 'USC00514830', '2017-06-20', 0.17, 79.0)
(7586, 'USC00514830', '2017-06-23', None, 76.0)
(7587, 'USC00514830', '2017-06-26', None, 80.0)
(7588, 'USC00514830', '2017-06-29', None, 76.0)
(7589, 'USC00514830', '2017-06-30', 0.0, 81.0)
(8971, 'USC00517948', '2017-06-02', None, 79.0)
(8972, 'USC00517948', '2017-06-05', None, 78.0)
(8973, 'USC00517948', '2017-06-06', None, 80.0)
(8974, 'USC00517948', '2017-06-07', None, 80.0)
(8975, 'USC00517948', '2017-06-08', None, 78.0)
(8976, 'USC00517948', '2017-06-09', None, 80.0)
(8977, 'USC00517948', '2017-06-13', None, 81.0)
(8978, 'USC00517948', '2017-06-14', None, 78.0)
(8979, 'USC00517948', '2017-06-15', None, 77.0)
(8980, 'USC00517948', '2017-06-16', None, 78.0)
(8981, 'USC00517948', '2017-06-19', None, 78.0)
(8982, 'USC00517948', '2017-06-20', None, 77.0)
(8983, 'USC00517948', '2017-06-21', None, 76.0)
(8984, 'USC00517948', '2017-06-22', 0.0, 81.0)
(8985, 'USC00517948', '2017-06-23', 0.0, 76.0)
(8986, 'USC00517948', '2017-06-26', None, 82.0)
(8987, 'USC00517948', '2017-06-27', 0.0, 80.0)
(8988, 'USC00517948', '2017-06-28', 0.0, 80.0)
(8989, 'USC00517948', '2017-06-29', 0.0, 79.0)
(8990, 'USC00517948', '2017-06-30', 0.12, 74.0)
(12112, 'USC00519523', '2017-06-01', 0.0, 79.0)
(12113, 'USC00519523', '2017-06-02', 0.0, 81.0)
(12114, 'USC00519523', '2017-06-03', 0.15, 79.0)
(12115, 'USC00519523', '2017-06-04', 0.0, 81.0)
(12116, 'USC00519523', '2017-06-05', 0.0, 78.0)
(12117, 'USC00519523', '2017-06-06', 0.0, 78.0)
(12118, 'USC00519523', '2017-06-07', 0.0, 78.0)
(12119, 'USC00519523', '2017-06-08', 0.0, 77.0)
(12120, 'USC00519523', '2017-06-09', 0.0, 78.0)
(12121, 'USC00519523', '2017-06-10', 0.13, 75.0)
(12122, 'USC00519523', '2017-06-11', 0.25, 81.0)
(12123, 'USC00519523', '2017-06-12', 0.14, 80.0)
(12124, 'USC00519523', '2017-06-13', 0.03, 77.0)
(12125, 'USC00519523', '2017-06-14', 0.06, 80.0)
(12126, 'USC00519523', '2017-06-15', 0.0, 78.0)
(12127, 'USC00519523', '2017-06-16', 0.0, 80.0)
(12128, 'USC00519523', '2017-06-17', 0.0, 77.0)
(12129, 'USC00519523', '2017-06-18', 0.0, 78.0)
(12130, 'USC00519523', '2017-06-19', 0.01, 78.0)
(12131, 'USC00519523', '2017-06-21', None, 80.0)
(12132, 'USC00519523', '2017-06-22', 0.0, 80.0)
(12133, 'USC00519523', '2017-06-23', 0.05, 79.0)
(12134, 'USC00519523', '2017-06-24', 0.0, 82.0)
(12135, 'USC00519523', '2017-06-25', 0.0, 80.0)
(12136, 'USC00519523', '2017-06-26', 0.0, 81.0)
(12137, 'USC00519523', '2017-06-27', 0.0, 81.0)
(12138, 'USC00519523', '2017-06-28', 0.0, 79.0)
(12139, 'USC00519523', '2017-06-29', 0.0, 78.0)
(12140, 'USC00519523', '2017-06-30', 0.07, 75.0)
(14890, 'USC00519281', '2017-06-01', 0.0, 80.0)
(14891, 'USC00519281', '2017-06-02', 0.09, 76.0)
(14892, 'USC00519281', '2017-06-03', 0.08, 76.0)
(14893, 'USC00519281', '2017-06-04', 0.13, 77.0)
(14894, 'USC00519281', '2017-06-05', 0.05, 75.0)
(14895, 'USC00519281', '2017-06-06', 0.0, 75.0)
(14896, 'USC00519281', '2017-06-07', 0.0, 75.0)
(14897, 'USC00519281', '2017-06-08', 0.0, 75.0)
(14898, 'USC00519281', '2017-06-09', 0.02, 72.0)
(14899, 'USC00519281', '2017-06-10', 0.62, 74.0)
(14900, 'USC00519281', '2017-06-11', 0.74, 74.0)
(14901, 'USC00519281', '2017-06-12', 0.24, 74.0)
(14902, 'USC00519281', '2017-06-13', 0.24, 76.0)
(14903, 'USC00519281', '2017-06-14', 0.22, 74.0)
(14904, 'USC00519281', '2017-06-15', 0.55, 75.0)
(14905, 'USC00519281', '2017-06-16', 0.06, 73.0)
(14906, 'USC00519281', '2017-06-17', 0.07, 79.0)
(14907, 'USC00519281', '2017-06-18', 0.24, 75.0)
(14908, 'USC00519281', '2017-06-19', 0.08, 72.0)
(14909, 'USC00519281', '2017-06-20', 0.0, 72.0)
(14910, 'USC00519281', '2017-06-21', 0.19, 74.0)
(14911, 'USC00519281', '2017-06-22', 0.06, 72.0)
(14912, 'USC00519281', '2017-06-23', 0.12, 72.0)
(14913, 'USC00519281', '2017-06-24', 0.36, 77.0)
(14914, 'USC00519281', '2017-06-25', 0.02, 71.0)
(14915, 'USC00519281', '2017-06-26', 0.06, 73.0)
(14916, 'USC00519281', '2017-06-27', 0.01, 76.0)
(14917, 'USC00519281', '2017-06-28', 0.0, 77.0)
(14918, 'USC00519281', '2017-06-29', 0.0, 76.0)
(14919, 'USC00519281', '2017-06-30', 0.01, 76.0)
(19470, 'USC00516128', '2017-06-01', 0.01, 74.0)
(19471, 'USC00516128', '2017-06-03', None, 74.0)
(19472, 'USC00516128', '2017-06-04', 0.82, 77.0)
(19473, 'USC00516128', '2017-06-05', 0.01, 74.0)
(19474, 'USC00516128', '2017-06-06', 0.0, 74.0)
(19475, 'USC00516128', '2017-06-07', 0.01, 79.0)
(19476, 'USC00516128', '2017-06-08', 0.0, 75.0)
(19477, 'USC00516128', '2017-06-10', None, 72.0)
(19478, 'USC00516128', '2017-06-11', 0.7, 76.0)
(19479, 'USC00516128', '2017-06-12', 0.81, 74.0)
(19480, 'USC00516128', '2017-06-13', 0.65, 73.0)
(19481, 'USC00516128', '2017-06-14', 0.81, 74.0)
(19482, 'USC00516128', '2017-06-15', 1.69, 77.0)
(19483, 'USC00516128', '2017-06-16', 0.1, 74.0)
(19484, 'USC00516128', '2017-06-17', 0.1, 72.0)
(19485, 'USC00516128', '2017-06-18', 0.7, 77.0)
(19486, 'USC00516128', '2017-06-19', 0.4, 76.0)
(19487, 'USC00516128', '2017-06-20', 0.31, 74.0)
(19488, 'USC00516128', '2017-06-21', 0.3, 75.0)
(19489, 'USC00516128', '2017-06-22', 0.28, 76.0)
(19490, 'USC00516128', '2017-06-23', 0.5, 71.0)
(19491, 'USC00516128', '2017-06-24', 0.22, 73.0)
(19492, 'USC00516128', '2017-06-25', 0.5, 79.0)
(19493, 'USC00516128', '2017-06-26', 0.02, 79.0)
(19494, 'USC00516128', '2017-06-27', 0.1, 74.0)
(19495, 'USC00516128', '2017-06-28', 0.02, 74.0)
(19496, 'USC00516128', '2017-06-29', 0.04, 76.0)
(19497, 'USC00516128', '2017-06-30', 0.2, 75.0)

In [25]:
june_list = [temp[3] for temp in results]
june_list

[]

In [24]:
june_df = pd.DataFrame(june_list)
june_df

Empty DataFrame
Columns: []
Index: []